##########################################################################
# Title:         Cloudbox: Olaris | Default Variables                    #
# Author(s):     l3uddz                                                  #
# Originally written by l3uddz, updated by Tom                           #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

olaris_name: olaris

################################
# Paths
################################

olaris_paths_folder: "{{ olaris_name }}"
olaris_paths_location: "/opt/{{ olaris_paths_folder }}"
olaris_rclone_config_location: "/home/{{ user.name }}/.config/rclone"

olaris_paths_folders_list:
  - "{{ olaris_paths_location }}"
  - "{{ olaris_rclone_config_location }}"

################################
# Web
################################

olaris_web_subdomain: "{{ olaris_name }}"
olaris_web_domain: "{{ user.domain }}"
olaris_web_port: "8080"
olaris_web_url: "{{ 'https://' + olaris_web_subdomain + '.' + olaris_web_domain }}"

################################
# Docker
################################

# Container
olaris_docker_container: "{{ olaris_name }}"

# Image
olaris_docker_image_pull: yes
olaris_docker_image_tag: "latest"
olaris_docker_image: "olaristv/olaris-server:{{ olaris_docker_image_tag }}"

# Ports
olaris_docker_ports_defaults:
  - "{{ olaris_web_port }}"
olaris_docker_ports_custom: []
olaris_docker_ports: "{{ olaris_docker_ports_defaults
  + olaris_docker_ports_custom }}"

# Volumes
olaris_docker_volumes_default:
  - "{{ olaris_paths_location }}:/home/olaris/.config/olaris"
  - "{{ olaris_rclone_config_location }}:/home/olaris/.config/rclone"
  - "/mnt:/mnt"
olaris_docker_volumes_custom: []
olaris_docker_volumes: "{{ olaris_docker_volumes_default
  + olaris_docker_volumes_custom }}"

# Devices
olaris_docker_devices_default: []
olaris_docker_devices_custom: []
olaris_docker_devices: "{{ olaris_docker_devices_default
  + olaris_docker_devices_custom }}"

# Hosts
olaris_docker_hosts_default: []
olaris_docker_hosts_custom: []
olaris_docker_hosts: "{{ olaris_docker_hosts_default | combine(olaris_docker_hosts_custom) }}"
